Port to vcpkg
DatabaseGroup/tree-similarity pull request #24
Opened 2023-04-16 12:28 UTC by remz1337

I ported this library to vcpkg package manager for easy install in other projects. For this, I add the install target in CMake, and fixed the relative paths of header files across the src folder.

Also updated the README for installation instruction with VCPKG.

2023-04-20 17:02 UTC, mateuszpawlik requested changes
All is fine. I'd only like some documentation links to using VCPKG.

2023-04-21 03:13 UTC, remz1337 commented on src/command_line/main.cc
> +  if (argc != 6) {
I copied the `main.cc` from the other branch so there shouldn't be any conflict when accepting both PRs

2023-04-21 03:14 UTC, remz1337 commented on README.md
> +This library has been ported to VCPKG package manager. To include in your project, install with ``./vcpkg install tree-similarity``, then include the library in your project's CMakeFile
Added a link to the Github repo, which provides all the necessary information to install it and get started

2023-04-21 03:16 UTC, remz1337 commented
Changes done!

2023-04-21 09:23 UTC, mateuszpawlik commented
@remz1337, please resolve the conflicts. Merging #23 must have caused it.

2023-04-23 18:35 UTC, remz1337 commented
Should be good now

2023-04-24 07:21 UTC, mateuszpawlik commented
Thank you @remz1337. I'm merging in.

2023-04-24 07:22 UTC, merged

2023-04-24 15:39 UTC, remz1337 commented
Thank you @mateuszpawlik. Can you add a tag/release of the current version? It will be easier to identify/follow future versions with vcpkg.
My open PR with vcpkg to include tree-similarity in their database:
https://github.com/microsoft/vcpkg/pull/30901

2023-04-27 09:16 UTC, mateuszpawlik commented
With @thuetter we scheduled a little hackathon, mainly for the documentation. Is it easy to update that tag on vcpkg side?

2023-04-27 13:38 UTC, remz1337 commented
pretty easy yes, just need to update the commit hash and version string in the portfile (json file defining the library in vcpkg). I would advise that you create a tag with the current HEAD (76e62627438ea603c9881221f7444c7cb5407b6d) that matches the version string in VCPKG (but it's not mandatory).

Any further revision/release of the library will also need to be updated in vcpkg (otherwise people installing from vcpkg will always download `v0.1`)